apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allure
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Eu-Pedro0ficial/HexaVault
    targetRevision: HEAD
    path: allure

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
